<?php

$estado = array(

    'acre' => [	
        "Rio Branco",	
        "Cruzeiro do Sul",	
        "Sena Madureira",	
        "Tarauacá",	
        "Feijó"
    ],


);




$estado['acre'][arrat_rand($estado['acre'])];
   

    var amapa = [
   "Macapá",	
   "Santana",	
   "Laranjal do Jari",	
   "Oiapoque",	
   "Mazagão"
    ];
    
    var amazonas = [	
   "Manaus",	
   "Parintins",	
   "Itacoatiara",	
   "Manacapuru",	
   "Coari"
    ];
   
   var bahia = [ 
   "Salvador",	
   "Feira de Santana",	
   "Vitória da Conquista",	
   "Camaçari",	
   "Itabuna"
   ];
   
   var ceara = [	
   "Fortaleza",	
   "Caucaia",	
   "Juazeiro do Norte",	
   "Maracanaú",	
   "Sobral"
   ];
   
   var distritoFederal = [	
   "Brasília"				
   ];
   
   var espirito = [ 
   "Santo",	
   "Serra",	
   "Vila Velha",	
   "Cariacica",	
   "Vitória"
   ];
   
    var goias = [	
   "Goiânia",	
   "Aparecida de Goiânia",	
   "Anapólis",	
   "Rio Verde",	
   "Luziânia"
    ];
   
    var maranhao = [	
    "São Luís",	
    "Imperatriz",	
    "São José do Ribamar",	
    "Caxias",	
    "Timon"
    ];
   
    var matoGrosso	= [
    "Cuiabá",	
    "Várzea Grande",	
    "Rondonópolis",	
    "Sinop",	
    "Tangará da Serra"
    ];
   
    var matoGrossoDoSul = [	
    "Campo Grande",	
    "Dourados",	
    "Três Lagoas",	
    "Corumbá",	
    "Ponta Porã"
    ];
   
   var minasGerais	= [
   "Belo Horizonte",	
   "Uberlândia",
   "Contagem",	
   "Juiz de Fora",	
   "Betim"
    ];
   
   var para = [	
   "Belém",	
   "Ananindeua",	
   "Santarém",	
   "Marabá",	
   "Parauapebas"
    ];
   
   var paraiba	= [
   "João Pessoa",	
   "Campina Grande",	
   "Santa Rita",
   "Patos",	
   "Bayeux"
    ];
   
   var parana	= [
   "Curitiba",	
   "Londrina",	
   "Maringá",	
   "Ponta Grossa",	
   "Cascavel"
    ];
   
   var pernambuco = [	
   "Recife",
   "Jaboatão dos Guararapes",
   "Olinda",	
   "Caruaru",	
   "Petrolina"
    ];
   
   var piaui = [
   "Teresina",	
   "Parnaíba",	
   "Picos",	
   "Piripiri",	
   "Floriano"
    ];
   
   var rioDeJaneiro	= [
   "Rio de Janeiro",	
   "São Gonçalo",	
   "Duque de Caxias",	
   "Nova Iguaçu",	
   "Niterói"
    ];
   
   var rioGrandeDoNorte	= [
   "Natal",	
   "Mossoró",	
   "Parnamirim",	
   "São Gonçalo do Amarante",	
   "Macaíba"
    ];
   
   var rioGrandeDoSul	= [
   "Porto Alegre",	
   "Caxias do Sul",	
   "Pelotas",	
   "Canoas",
   "Santa Maria"
    ];
   
   var rondonia	= [
   "Porto Velho",	
   "Ji-Paraná",	
   "Ariquemes",	
   "Vilhena",	
   "Cacoal"
    ];
   
   var roraima	= [
   "Boa Vista",	
   "Rorainópolis",	
   "Caracaraí",	
   "Alto Alegre",	
   "Mucajaí"
    ];
   
   var santaCatarina	= [
   "Joinville",	
   "Florianópolis",	
   "Blumenau",	
   "São José",	
   "Criciúma"
    ];
   
   var saoPaulo	= [
   "São Paulo",	
   "Guarulhos",	
   "Campinas",	
   "São Bernardo do Campo",	
   "Santo André"
    ];
   
   var sergipe	= [
   "Aracaju",	
   "Nossa Senhora do Socorro",	
   "Lagarto",	
   "Itabaiana",	
   "São Cristovão"
    ];
   
   var tocantins	= [
   "Palmas",	
   "Araguaína",
   "Gurupi",
   "Porto Nacional",
   "Paraíso do Tocantins" 
   ];

var faixa_cep = 
[
    '999',
    '699',
    '570',
    '690',
    '689',
    '400',
    '600',
    '700',
    '290',
    '728',
    '650',
    '300',
    '790',
    '780',
    '660',
    '580',
    '500',
    '640',
    '800',
    '200',
    '5900',
    '768',
    '693',
    '900',
    '880',
    '490',
    '010',
    '770'
]

var inicio_telefone = [
    "32",
    "999"
]

var nome = [
    "Alice",	
    "Miguel",
    "Sophia",
    "Arthur",
    "Júlia",	
    "Davi",
    "Laura",	
    "Pedro",
    "Isabella",	
    "Bernardo",
    "Manuela",	
    "Gabriel",
    "Luiza",	
    "Lucas",
    "Helena",	
    "Matheus",
    "Valentina",	
    "Heitor",
    "Giovanna",	
    "Rafael",
    "Maria Eduarda",	
    "Enzo",
    "Beatriz",	
    "Nicolas",
    "Maria Clara",	
    "Lorenzo",
    "Maria Luiza",	
    "Guilherme",
    "Heloísa",	
    "Samuel",
    "Mariana",	
    "Theo",
    "Lara",
    "Felipe",
    "Lívia",	
    "Gustavo",
    "Lorena",	
    "Henrique",
    "Ana Clara",	
    "João Pedro",
    "Isadora",	
    "João Lucas",
    "Rafaela",	
    "Daniel",
    "Sarah",	
    "Murilo",
    "Yasmin",
    "Vitor",
    "Ana Luiza",	
    "Pedro Henrique",
    "Letícia",	
    "Eduardo",
    "Nicole",	
    "Leonardo",
    "Gabriela",	
    "Pietro",
    "Isabelly",	
    "Benjamin",
    "Melissa",	
    "Isaac",
    "Cecília",	
    "João",
    "Esther",	
    "Joaquim",
    "Ana Júlia",	
    "Lucca",
    "Emanuelly",	
    "Caio",
    "Clara",	
    "Vinicius",
    "Marina",
    "Cauã",
    "Rebeca",	
    "Bryan",
    "Vitória",	
    "João Miguel",
    "Isis",	
    "Vicente",
    "Lavínia",	
    "Francisco",
    "Maria",	
    "Antônio",
    "Bianca",	
    "Benício",
    "Ana Beatriz",	
    "João Vitor",
    "Larissa",	
    "Enzo Gabriel",
    "Maria Fernanda",	
    "Davi Lucas",
    "Catarina",	
    "Davi Lucca",
    "Alícia",	
    "Thiago",
    "Maria Alice",	
    "Thomas",
    "Amanda",
    "Emanuel",
    "Ana",	
    "Enrico"
];

var sobrenome = [
    "Alves",
    "Monteiro",
    "Novaes",
    "Mendes",
    "Barros",
    "Freitas",
    "Barbosa",
    "Pinto",
    "Moura",
    "Cavalcanti",
    "Dias",
    "Castro",
    "Campos",
    "Cardoso",
    "Silva",
    "Souza",
    "Costa",
    "Santos",
    "Oliveira",
    "Pereira",
    "Rodrigues",
    "Almeida",
    "Nascimento",
    "Lima",
    "Araújo",
    "Fernandes",
    "Carvalho",
    "Gomes",
    "Martins",
    "Rocha",
    "Ribeiro",
    "Rezende",
    "Sales",
    "Peixoto",
    "Fogaça",
    "Porto",
    "Ribeiro",
    "Duarte",
    "Moraes",
    "Ramos",
    "Pereira",
    "Ferreira",
    "Silveira",
    "Moreira",
    "Teixeira",
    "Caldeira",
    "Vieira",
    "Nogueira",
    "da Costa",
    "da Rocha",
    "da Cruz",
    "da Cunha",
    "da Mata",
    "da Rosa",
    "da Mota",
    "da Paz",
    "da Luz",
    "da Conceição",
    "das Neves",
    "Fernandes",
    "Gonçalves",
    "Rodrigues",
    "Martins",
    "Lopes",
    "Gomes",
    "Mendes",
    "Nunes",
    "Carvalho",
    "Melo",
    "Cardoso",
    "Pires",
    "Jesus",
    "Aragão",
    "Viana",
    "Farias"
]
var nomeCompleto = [];

var nomeGenero = [
    "Ação",
    "Animação",
    "Aventura",
    "Comédia",
    "Comédia Romântica",
    "Comédia Dramática",
    "Dança",
    "Documentário",
    "Drama",
    "Espionagem",
    "Fantasia",
    "Faroeste",
    "Ficção Científica",
    "Guerra",
    "Musical",
    "Policial",
    "Romance",
    "Suspense",
    "Terror"
];

var enderecos = [] //540 enderecos  (levar em consideração tamanho do estado);

var rua = 
[
    "Rua Dois",
    "Rua Três",
    "Rua Um",
    "Rua B",
    "Rua Quatro",
    "Rua Principal",
    "Rua A",
    "Rua C",
    "Rua Cinco",
    "Rua Sei",
    "Rua D",
    "Rua Sete",
    "Rua Oito",
    "Rua E",
    "Rua F",
    "Rua Nove",
    "Rua Dez",
    "Rua G",
    "Rua São José",
    "Rua Onze",
    "Rua H",
    "Rua São Paulo",
    "Rua Doze",
    "Rua Treze ",
    "Rua Santo Antônio",
    "Avenida Brasil",
    "Rua I",
    "Rua 2",
    "Rua 1",
    "Rua 3",
    "Rua Sao Pedro",
    "Rua Quinze",
    "Rua Sao João",
    "Rua J",
    "Rua Quatorze",
    "Rua Sao Francisco",
    "Rua Sete de Setembro",
    "Rua 4",
    "Rua Dezesseis",
    "Rua Quinze De Novembro",
    "Rua 5",
    "Rua Tiradentes",
    "Rua Dezessete",
    "Rua 6",
    "Rua L",
    "Rua Vinte",
    "Rua Bahia",
    "Rua Amazonas",
    "Rua Dezoito",
    "Rua Sao Sebastiao",
    "Rua Parana",
    "Rua Bela Vista",
    "Rua M",
    "Rua 7",
    "Rua Santa Luzia",
    "Rua Sao Jorge",
    "Rua Dezenove",
    "Rua Castro Alves",
    "Rua Duque De Caxias",
    "Rua Projetada",
    "Rua Rui Barbosa",
    "Rua Santa Catarina",
    "Rua Minas Gerais",
    "Rua N",
    "Rua Santos Dumont",
    "Rua 8",
    "Rua Espirito Santo",
    "Rua Vinte e Um",
    "Rua Vinte e Dois",
    "Rua Da Paz",
    "Rua Treze De Maio",
    "Rua K",
    "Rua Rio De Janeiro",
    "Rua Goias",
    "Rua Ceara",
    "Rua 10",
    "Rua Belo Horizonte",
    "Rua Das Flores",
    "Rua Sergipe",
    "Rua Vitoria",
    "Rua José Bonifácio",
    "Rua Pernambuco",
    "Rua Piauí ",
    "Rua Vinte e Três",
    "Rua 9 ",
    "Rua Mato Grosso",
    "Rua Santa Maria",
    "Rua Dom Pedro II",
    "Rua Primeiro de Maio",
    "Rua Pará",
    "Rua Maranhão",
    "Rua Alagoas",
    "Rua Boa Vista",
    "Rua Sao Luiz",
    "Rua Vinte e Quatro",
    "Rua Paraíba",
    "Rua 12",
    "Rua O ",
    "Rua Santa Rita",
    "Rua 11"
];
var bairro =
[
    "Acácia",
    "Acácias",
    "Alcídes Rabello",
    "Alcídes Rabelo",
    "Alice Maia",
    "Alterosa",
    "Alterosas",
    "Alto Boa Vista",
    "Alto São João",
    "Amazonas",
    "Antônio Canela",
    "Antônio Pimenta",
    "Augusta Mota",
    "Barcelona Park",
    "Bela Vista",
    "Brasília",
    "Camilo Prates",
    "Cândida Câmara",
    "Canelas",
    "Carmelo",
    "Centro",
    "Chácara Recanto dos Araçás",
    "Chiquinho Guimarães",
    "Cidade Cristo Rei",
    "Cidade Ind",
    "Cidade Industrial",
    "Cidade Nova",
    "Cidade Santa Maria",
    "Cintra",
    "Ciro Anjos",
    "Clarindo Lopes",
    "Conjunto Chiquinho Guimarães",
    "Conjunto Ciro dos Anjos",
    "Conjunto Clarice Alves Vieira",
    "Conjunto Cristo Rei",
    "Conjunto Habitacional Joaquim Costa",
    "Conjunto Habitacional José C Machad",
    "Conjunto Jk II",
    "Conjunto Joaquim Costa",
    "Conjunto José Carlos Lima",
    "Conjunto Residencial Jk",
    "Delfino Magalhães",
    "Distrito Industrial",
    "Dona Gregoria",
    "Doutor João Alves",
    "Edgar Pereira",
    "Eldorado",
    "Esplanada",
    "Floresta",
    "Francisco Peres I",
    "Funcionários",
    "Guarujá",
    "Guilhermina",
    "Ibituruna",
    "Independência",
    "Interlagos",
    "Itatiaia",
    "Jaraguá",
    "Jaraguá I",
    "Jaraguá II",
    "Jardim Alvorada",
    "Jardim Brasil",
    "Jardim Eldorado",
    "Jardim Europa",
    "Jardim Liberdade",
    "Jardim Palmeiras",
    "Jardim Panorama",
    "Jardim Primavera",
    "Jardim São Geraldo",
    "Jardim São Luís",
    "Jardim São Luiz",
    "Jk",
    "João Alves",
    "João Botelho",
    "João Gordo",
    "José Carlos Vale Lima",
    "Lourdes",
    "Major Prates",
    "Mangues",
    "Maracanã",
    "Maracanã 2",
    "Maria Cândida",
    "Melo",
    "Monte Alegre",
    "Monte Carmelo",
    "Montes Claros",
    "Morada da Serra",
    "Morada do Parque",
    "Morada do Sol",
    "Morada Parque",
    "Morada Serra",
    "Morada Sol",
    "Morada Suboficial Sol",
    "Morrinhos",
    "Nossa Senhora Aparecida",
    "Nossa Senhora de Fátima",
    "Nossa Senhora Graças",
    "Novo Delfino",
    "Panorama II",
    "Parque Ecologista Pampulha",
    "Parque Morada Sol",
    "Planalto",
    "Planalto II",
    "Povoação Pau Dom Óleo",
    "Prolg Todos Os Santos",
    "Raul Lourenço",
    "Recanto Araçás",
    "Regina Peres",
    "Renascença",
    "Roxo Verde",
    "Sagrada Família",
    "Santa Cecília",
    "Santa Eugênia",
    "Santa Laura",
    "Santa Lúcia",
    "Santa Lúcia II",
    "Santa Maria",
    "Santa Rafaela",
    "Santa Rita",
    "Santa Rita I",
    "Santa Rita II",
    "Santo Amaro",
    "Santo Antônio",
    "Santo Antônio II",
    "Santo Expedito",
    "Santo Inácio",
    "Santos Reis",
    "São Bento",
    "São Francisco Assis",
    "São Geraldo",
    "São João",
    "São José",
    "São Judas Tadeu",
    "São Judas Tadeu I",
    "Sion",
    "Sion II",
    "Sumaré",
    "Tancredo Neves",
    "Tancredo Neves I",
    "Todos Os Santos",
    "Todos Santos",
    "Universitário",
    "Vargem Grande II",
    "Vera Cruz",
    "Vila Anália",
    "Vila Antônio Canela",
    "Vila Antônio Narciso",
    "Vila Atlântica",
    "Vila Atlântica II",
    "Vila Atlântida",
    "Vila Áurea",
    "Vila Brasília",
    "Vila Campos",
    "Vila Exposição",
    "Vila Greice",
    "Vila Guilhermina",
    "Vila Ipiranga",
    "Vila Luíza",
    "Vila Maria Cândida",
    "Vila Mauriceia",
    "Vila Nova Morada",
    "Vila Oliveira",
    "Vila Regina",
    "Vila Santa Cruz",
    "Vila Santa Maria",
    "Vila São Fco Assis",
    "Vila Setor Bomfim",
    "Vila Sion",
    "Vila Sion II",
    "Vila Sumaré",
    "Vila Telma",
    "Vila Toncheff",
    "Vila Tupã",
    "Vilage Lago",
    "Vilage Lago II",
    "Vilage Lago Popular",
    "Village do Lago I",
    "Village do Lago Ii",
    "Village Lago I"
];

var filmes = [
    'Um Sonho de Liberdade',
    'O Poderoso Chefão',
    'Batman: O Cavaleiro das Trevas',
    '12 Homens e uma Sentença',
    'O Senhor dos Anéis: O Retorno do Rei',
    'Clube da Luta',
    'A Origem',
    'Matrix',
    'Guerra nas Estrelas',
    'Cidade de Deus',
    'O Silêncio dos Inocentes',
    'Interestelar',
    'Psicose',
    'Os Tempos Modernos',
    'De Volta para o Futuro',
    'O Grande Truque',
    'O Rei Leão',
    'WALL-E',
    'Coração Valente',
    'O Fabuloso Destino de Amélie Poulain',
    'Laranja Mecânica',
    'Toy Story',
    'Bastardos Inglórios',
    'Up: Altas Aventuras',
    'Duro de Matar',
    'O Labirinto do Fauno',
    'Divertida Mente',
    'O Sexto Sentido',
    'Procurando Nemo',
    'Como Treinar o Seu Dragão',
    'Logan',
    'Garota Exemplar',
    'Ilha do Medo',
    '12 Anos de Escravidão',
    'As Aventuras de Pi',
    'O Mágico de Oz',
    'Histórias Cruzadas',
    'Piratas do Caribe: A Maldição do Pérola Negra',
    'Tubarão',
    'O Exterminador do Futuro',
    'O Show de Truman',
    'Jurassic Park: O Parque dos Dinossauros',
    'Kill Bill: Volume 1',
    'O Franco Atirador',
    'Gran Torino ',
    'O Quarto de Jack',
    'Batman Begins',
    'Indiana Jones e a Última Cruzada',
    'Metrópolis'
]//50 filmes

var filmes_generos = [
    '9',
    '9',
    '3',
    '1',
    '3',
    '9',
    '13',
    '1',
    '3',
    '9',
    '18',
    '13',
    '18',
    '4',
    '13',
    '18',
    '2',
    '2',
    '3',
    '9',
    '9',
    '2',
    '1',
    '2',
    '1',
    '3',
    '2',
    '18',
    '2',
    '2',
    '1',
    '18',
    '18',
    '9',
    '2',
    'O3',
    '9',
    '3',
    '18',
    '1',
    '9',
    '3',
    '1',
    '1',
    '1',
    '9',
    '1',
    '3',
    '13',
]

var possiveis_precos = ['10.00', '15.00', '20.50','30.50'];